
const products = [
    {
      id: 1,
      title: 'Product 1',
      description: 'Description for Product 1',
      price: 20,
      category: 'Category A',
      image : 'nokia.jpg',
    },
    {
      id: 2,
      title: 'Product 2',
      description: 'Description for Product 2',
      price: 25,
      category: 'Category B',
      image: 'nokia.jpg',
    },
    {
        id: 3,
        title: 'Product 3',
        description: 'Description for Product 3',
        price: 30,
        category: 'Category C',
        image: 'nokia.jpg',
      },
      {
        id: 4,
        title: 'Product 4',
        description: 'Description for Product 4',
        price: 35,
        category: 'Category D',
        image: 'nokia.jpg',
      },
      {
        id: 5,
        title: 'Product 5',
        description: 'Description for Product 5',
        price: 40,
        category: 'Category A',
        image: 'nokia.jpg',
      },
      {
        id: 6,
        title: 'Product 6',
        description: 'Description for Product 6',
        price: 45,
        category: 'Category B',
        image: 'nokia.jpg',
      },
      {
          id: 7,
          title: 'Product 7',
          description: 'Description for Product 7',
          price: 50,
          category: 'Category C',
          image: 'nokia.jpg',
        },
        {
          id: 8,
          title: 'Product 8',
          description: 'Description for Product 8',
          price: 55,
          category: 'Category D',
          image: 'nokia.jpg',
        },
        {
          id: 9,
          title: 'Product 9',
          description: 'Description for Product 9',
          price: 60,
          category: 'Category A',
          image: 'nokia.jpg',
        },
        {
          id: 10,
          title: 'Product 10',
          description: 'Description for Product 10',
          price: 65,
          category: 'Category B',
          image: 'nokia.jpg',
        },
        {
            id: 11,
            title: 'Product 11',
            description: 'Description for Product 11',
            price: 70,
            category: 'Category C',
            image: 'nokia.jpg',
          },
          {
            id: 12,
            title: 'Product 12',
            description: 'Description for Product 12',
            price: 75,
            category: 'Category D',
            image: 'nokia.jpg',
          },
          {
            id: 13,
            title: 'Product 13',
            description: 'Description for Product 13',
            price: 80,
            category: 'Category A',
            image: 'nokia.jpg',
          },
          {
            id: 14,
            title: 'Product 14',
            description: 'Description for Product 14',
            price: 85,
            category: 'Category B',
            image: 'nokia.jpg',
          },
          {
              id: 15,
              title: 'Product 15',
              description: 'Description for Product 15',
              price: 90,
              category: 'Category C',
              image: 'nokia.jpg',
            },
            {
              id: 16,
              title: 'Product 16',
              description: 'Description for Product 16',
              price: 95,
              category: 'Category D',
              image: 'nokia.jpg',
            },
            {
              id: 17,
              title: 'Product 17',
              description: 'Description for Product 17',
              price: 100,
              category: 'Category A',
              image: 'nokia.jpg',
            },
            {
              id: 18,
              title: 'Product 18',
              description: 'Description for Product 18',
              price: 105,
              category: 'Category B',
              image: 'nokia.jpg',
            },
            {
                id: 19,
                title: 'Product 19',
                description: 'Description for Product 19',
                price: 110,
                category: 'Category C',
                image: 'nokia.jpg',
              },
              {
                id: 20,
                title: 'Product 20',
                description: 'Description for Product 20',
                price: 115,
                category: 'Category D',
                image: 'nokia.jpg',
              },
              {
                id: 21,
                title: 'Product 21',
                description: 'Description for Product 21',
                price: 120,
                category: 'Category A',
                image:'nokia.jpg',
              },
              {
                id: 22,
                title: 'Product 22',
                description: 'Description for Product 22',
                price: 125,
                category: 'Category B',
                image: 'nokia.jpg',
              },
              {
                  id: 23,
                  title: 'Product 23',
                  description: 'Description for Product 23',
                  price: 130,
                  category: 'Category C',
                  image:'nokia.jpg',
                },
                {
                  id: 24,
                  title: 'Product 24',
                  description: 'Description for Product 24',
                  price: 135,
                  category: 'Category D',
                  image: 'nokia.jpg',
                },
                {
                  id: 25,
                  title: 'Product 25',
                  description: 'Description for Product 25',
                  price: 140,
                  category: 'Category A',
                  image:'nokia.jpg',
                },
                {
                  id: 26,
                  title: 'Product 26',
                  description: 'Description for Product 26',
                  price: 145,
                  category: 'Category B',
                  image: 'nokia.jpg',
                },
                {
                    id: 27,
                    title: 'Product 27',
                    description: 'Description for Product 27',
                    price: 150,
                    category: 'Category C',
                    image: 'nokia.jpg',
                  },
                  {
                    id: 28,
                    title: 'Product 28',
                    description: 'Description for Product 28',
                    price: 155,
                    category: 'Category D',
                    image: 'nokia.jpg',
                  },
      
 
  ];
  
  export default products;
  